---
# This is a basic workflow to help you get started with Actions

name: placeholder, test, build and publish

on:   # yamllint disable-line rule:truthy
  # Triggers on push or pull request events but only for the main branch
  push:
    branches: ['**']
    paths:
      - '**'
      - '!Dockerfile.spell'
      - '!.github/workflows/docker-spell.yml'
      - '!Dockerfile.rmarkdown'
      - '!.github/workflows/docker-rmarkdown.yml'
  pull_request:
    branches: [main]
    paths:
      - '**'
      - '!Dockerfile.spell'
      - '!.github/workflows/docker-spell.yml'
      - '!Dockerfile.rmarkdown'
      - '!.github/workflows/docker-rmarkdown.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  SPELL_IMAGE_NAME: ghcr.io/bbourdin/resume-spell:${GITHUB_REF_NAME}
  RMARKDOWN_IMAGE_NAME: ghcr.io/bbourdin/resume-rmarkdown:${GITHUB_REF_NAME}

jobs:
  build-placeholder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Replace data (default) - resume
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: Benoit-Bourdin-resume.rmd.j2
          output_file: Benoit-Bourdin-resume.rmd
          data_file: resume-data.yml
          data_format: yaml
      - name: Replace data (default) - slide
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: Benoit-Bourdin-slide.md.j2
          output_file: Benoit-Bourdin-slide.md
          data_file: resume-data.yml
          data_format: yaml
      - name: upload generated markdown as artifact
        uses: actions/upload-artifact@v2
        with:
          name: Benoit-Bourdin-resume-rmarkdown
          path: |
            Benoit-Bourdin-resume.rmd
            Benoit-Bourdin-slide.md

  lint-markdown:
    runs-on: ubuntu-latest
    needs: build-placeholder
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: Benoit-Bourdin-resume-rmarkdown
      - name: List generated files
        run: |
          ls -l Benoit-Bourdin-resume.rmd Benoit-Bourdin-slide.md
          echo ${GITHUB_REF_NAME}
          echo end
      - name: Lint - markdown files
        uses: actionshub/markdownlint@main
        with:
          path: Benoit-Bourdin-resume.rmd Benoit-Bourdin-slide.md README.md

  get_spell_image_name:
    runs-on: ubuntu-latest
    outputs:
      var: ${{ steps.save_var.outputs.var }}
    steps:
      - id: save_var
        run: echo "::set-output name=var::${{ env.SPELL_IMAGE_NAME }}"

  markdown-spell-check:
    runs-on: ubuntu-latest
    needs: [build-placeholder, get_spell_image_name]
    container:
      image: ${{ needs.get_spell_image_name.outputs.var }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: Benoit-Bourdin-resume-rmarkdown
      - name: Run mdspell
        run: |
          find . -name "*.md" -o -name "*.rmd" \
          | xargs mdspell -n -a -r --en-us --dictionary dictionary/en_US-large

  marp-build:
    runs-on: ubuntu-latest
    needs: [build-placeholder]
    container:
      image: marpteam/marp-cli
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: Benoit-Bourdin-resume-rmarkdown
      - name: Run marp
        run: |
          alias marp="node /home/marp/.cli/marp-cli.js"
          marp Benoit-Bourdin-slide.md
          marp --pptx --allow-local-files Benoit-Bourdin-slide.md
          marp --pdf --allow-local-files Benoit-Bourdin-slide.md
          marp --image png --allow-local-files Benoit-Bourdin-slide.md
          ls -latr
          rm -rf output
          mkdir -p output/
          mv Benoit-Bourdin-slide.html Benoit-Bourdin-slide.pptx \
            Benoit-Bourdin-slide.pdf Benoit-Bourdin-slide.png output/
      - name: upload generated slides as artifact
        uses: actions/upload-artifact@v2
        with:
          name: Benoit-Bourdin-resume-slide
          path: output/**

  get_rmarkdown_image_name:
    runs-on: ubuntu-latest
    outputs:
      var: ${{ steps.save_var.outputs.var }}
    steps:
      - id: save_var
        run: echo "::set-output name=var::${{ env.RMARKDOWN_IMAGE_NAME }}"

  rmarkdown-build:
    runs-on: ubuntu-latest
    needs: [marp-build, get_rmarkdown_image_name]
    container:
      image: ${{ needs.get_rmarkdown_image_name.outputs.var }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: Benoit-Bourdin-resume-rmarkdown
      - uses: actions/download-artifact@v2
        with:
          name: Benoit-Bourdin-resume-slide
          path: output/
      - name: Run R
        run: |
          ls -latr
          mv -f output/Benoit-Bourdin-slide.png .
          R -e 'rmarkdown::render("Benoit-Bourdin-resume.rmd",
            output_format="all")'
          ls -latr
          rm -rf output
          mkdir -p output/
          mv -f Benoit-Bourdin-resume.html index.html
          mv index.html Benoit-Bourdin-resume.md Benoit-Bourdin-resume.pdf \
            Benoit-Bourdin-resume.docx resume-timeline.png \
            Benoit-Bourdin-resume_files output/
      - name: upload generated slides as artifact
        uses: actions/upload-artifact@v2
        with:
          name: Benoit-Bourdin-resume
          path: output/**

  deploy-gh-pages:
    runs-on: ubuntu-latest
    needs: [rmarkdown-build, marp-build]
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: Benoit-Bourdin-resume
          path: output/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        # if: ${{ github.ref == 'refs/heads/main' }} # only publish from main 
        with:
          folder: output # The folder the action should deploy.
