# This is a basic workflow to help you get started with Actions

name: placeholder, test, build and publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint - yaml files
        uses: ibiqlik/action-yamllint@v3

  placeholder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Replace data (default) - resume
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: Benoit-Bourdin-resume.rmd.j2
          output_file: Benoit-Bourdin-resume.rmd
          data_file: resume-data.yml
          data_format: yaml    
      - name: Replace data (default) - slide
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: Benoit-Bourdin-slide.md.j2
          output_file: Benoit-Bourdin-slide.md
          data_file: resume-data.yml
          data_format: yaml
      - name: Cache documents with replaced data
        uses: actions/cache@v2
        id: restore-markdown
        with:
          path: "Benoit-Bourdin-resume.rmd Benoit-Bourdin-slide.md README.md"
          key: ${{ runner.os }}-resume-markdown

  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache documents with replaced data
        uses: actions/cache@v2
        id: restore-markdown
        with:
          path: "Benoit-Bourdin-resume.rmd Benoit-Bourdin-slide.md README.md"
          key: ${{ runner.os }}-resume-markdown
      - name: Lint - markdown files
        uses: actionshub/markdownlint@main
        with:
          path: "Benoit-Bourdin-resume.rmd Benoit-Bourdin-slide.md README.md"

  markdown-spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache documents with replaced data
        uses: actions/cache@v2
        id: restore-markdown
        with:
          path: "Benoit-Bourdin-resume.rmd Benoit-Bourdin-slide.md README.md"
          key: ${{ runner.os }}-resume-markdown
      - name: Install Node.js 12
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
      - name: Install markdown-spellcheck
        run: npm install -g markdown-spellcheck
      - name: Run mdspell
        run: find . -name "*.md" -o -name "*.rmd" | xargs mdspell -n -a -r --en-us --dictionary dictionary/en_US-large
